Service layer tests were added:
Successfull case: We return the exact productIdand stock saved in the DB
Exception: when no data found, a ResourceNotFound exception is raised.